/**
 * Centralized API response codes. One code per success/error case in the backend.
 * Used by ResponseFactory to ensure consistent responses.
 */
export const ApiCodes = {
  // ── Generic ───────────────────────────────────────────────────────────────
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // ── Auth ───────────────────────────────────────────────────────────────────
  USER_REGISTERED: 'USER_REGISTERED',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  VERIFICATION_EMAIL_SENT: 'VERIFICATION_EMAIL_SENT',
  PASSWORD_RESET_EMAIL_SENT: 'PASSWORD_RESET_EMAIL_SENT',
  PASSWORD_RESET: 'PASSWORD_RESET',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  REFRESH_SUCCESS: 'REFRESH_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  USER_INFO_RETRIEVED: 'USER_INFO_RETRIEVED',
  USER_PROFILE_RETRIEVED: 'USER_PROFILE_RETRIEVED',
  USERNAME_CHECK_RESULT: 'USERNAME_CHECK_RESULT',
  USERS_SEARCH_SUCCESS: 'USERS_SEARCH_SUCCESS',
  USER_PUBLIC_PROFILE_RETRIEVED: 'USER_PUBLIC_PROFILE_RETRIEVED',
  USER_PROFILE_UPDATED: 'USER_PROFILE_UPDATED',

  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  INVALID_VERIFICATION_TOKEN: 'INVALID_VERIFICATION_TOKEN',
  VERIFICATION_TOKEN_ALREADY_USED: 'VERIFICATION_TOKEN_ALREADY_USED',
  VERIFICATION_TOKEN_EXPIRED: 'VERIFICATION_TOKEN_EXPIRED',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  RESET_TOKEN_ALREADY_USED: 'RESET_TOKEN_ALREADY_USED',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  REFRESH_TOKEN_NOT_FOUND: 'REFRESH_TOKEN_NOT_FOUND',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USERNAME_INVALID_LENGTH: 'USERNAME_INVALID_LENGTH',
  USERNAME_INVALID_CHARS: 'USERNAME_INVALID_CHARS',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  SEARCH_QUERY_TOO_SHORT: 'SEARCH_QUERY_TOO_SHORT',

  // ── Activities ────────────────────────────────────────────────────────────
  ACTIVITY_CREATED: 'ACTIVITY_CREATED',
  ACTIVITY_LIST_RETRIEVED: 'ACTIVITY_LIST_RETRIEVED',
  ACTIVITY_RETRIEVED: 'ACTIVITY_RETRIEVED',
  ACTIVITY_PARTICIPANTS_LIST_RETRIEVED: 'ACTIVITY_PARTICIPANTS_LIST_RETRIEVED',
  ACTIVITY_UPDATED: 'ACTIVITY_UPDATED',
  ACTIVITY_DELETED: 'ACTIVITY_DELETED',

  ACTIVITY_NOT_FOUND: 'ACTIVITY_NOT_FOUND',
  ACTIVITY_NOT_ACTIVE: 'ACTIVITY_NOT_ACTIVE',
  ACTIVITY_ALREADY_ENDED: 'ACTIVITY_ALREADY_ENDED',
  ACTIVITY_MODIFY_FORBIDDEN: 'ACTIVITY_MODIFY_FORBIDDEN',

  // ── Activity teams ───────────────────────────────────────────────────────
  ACTIVITY_TEAM_CREATED: 'ACTIVITY_TEAM_CREATED',
  ACTIVITY_TEAM_LIST_RETRIEVED: 'ACTIVITY_TEAM_LIST_RETRIEVED',
  ACTIVITY_TEAM_RETRIEVED: 'ACTIVITY_TEAM_RETRIEVED',
  ACTIVITY_TEAM_UPDATED: 'ACTIVITY_TEAM_UPDATED',
  ACTIVITY_TEAM_DELETED: 'ACTIVITY_TEAM_DELETED',

  ACTIVITY_TEAM_NOT_FOUND: 'ACTIVITY_TEAM_NOT_FOUND',
  ACTIVITY_TEAM_MEMBERS_LIST_RETRIEVED: 'ACTIVITY_TEAM_MEMBERS_LIST_RETRIEVED',
  ACTIVITY_TEAM_MEMBER_ADDED: 'ACTIVITY_TEAM_MEMBER_ADDED',
  ACTIVITY_TEAM_MEMBER_REMOVED: 'ACTIVITY_TEAM_MEMBER_REMOVED',
  ACTIVITY_TEAM_MEMBER_CAPTAIN_UPDATED: 'ACTIVITY_TEAM_MEMBER_CAPTAIN_UPDATED',

  ACTIVITY_TEAM_MEMBER_NOT_FOUND: 'ACTIVITY_TEAM_MEMBER_NOT_FOUND',
  PARTICIPATION_ALREADY_IN_TEAM: 'PARTICIPATION_ALREADY_IN_TEAM',
  PARTICIPATION_NOT_IN_ACTIVITY: 'PARTICIPATION_NOT_IN_ACTIVITY',

  // ── Participations ────────────────────────────────────────────────────────
  PARTICIPANT_ADDED: 'PARTICIPANT_ADDED',
  PARTICIPANT_ROLE_UPDATED: 'PARTICIPANT_ROLE_UPDATED',
  PARTICIPANT_REMOVED: 'PARTICIPANT_REMOVED',
  ACTIVITY_LEFT: 'ACTIVITY_LEFT',

  ACTIVITY_FULL: 'ACTIVITY_FULL',
  PARTICIPATION_NOT_FOUND: 'PARTICIPATION_NOT_FOUND',
  ACTIVE_PARTICIPATION_NOT_FOUND: 'ACTIVE_PARTICIPATION_NOT_FOUND',
  CANNOT_CHANGE_OWN_ROLE: 'CANNOT_CHANGE_OWN_ROLE',
  ONLY_REGISTERED_CAN_BE_HOST: 'ONLY_REGISTERED_CAN_BE_HOST',
  CANNOT_REMOVE_HOST: 'CANNOT_REMOVE_HOST',
  NOT_ACTIVE_PARTICIPANT: 'NOT_ACTIVE_PARTICIPANT',
  CANNOT_REMOVE_SOLE_HOST: 'CANNOT_REMOVE_SOLE_HOST',
  USER_ALREADY_PARTICIPANT: 'USER_ALREADY_PARTICIPANT',
  EXTERNAL_CONTACT_ALREADY_PARTICIPANT: 'EXTERNAL_CONTACT_ALREADY_PARTICIPANT',

  // ── External contacts ──────────────────────────────────────────────────────
  EXTERNAL_CONTACT_CREATED: 'EXTERNAL_CONTACT_CREATED',
  EXTERNAL_CONTACT_LIST_RETRIEVED: 'EXTERNAL_CONTACT_LIST_RETRIEVED',
  EXTERNAL_CONTACT_RETRIEVED: 'EXTERNAL_CONTACT_RETRIEVED',
  EXTERNAL_CONTACT_UPDATED: 'EXTERNAL_CONTACT_UPDATED',
  EXTERNAL_CONTACT_DELETED: 'EXTERNAL_CONTACT_DELETED',

  EXTERNAL_CONTACT_NOT_FOUND: 'EXTERNAL_CONTACT_NOT_FOUND',

  // ── Contacts ───────────────────────────────────────────────────────────────
  CONTACT_ADDED: 'CONTACT_ADDED',
  CONTACT_LIST_RETRIEVED: 'CONTACT_LIST_RETRIEVED',
  CONTACT_REMOVED: 'CONTACT_REMOVED',
  CONTACT_BATCH_REMOVED: 'CONTACT_BATCH_REMOVED',

  CONTACT_USER_OR_EXTERNAL_REQUIRED: 'CONTACT_USER_OR_EXTERNAL_REQUIRED',
  CONTACT_BOTH_PROVIDED: 'CONTACT_BOTH_PROVIDED',
  CONTACT_CANNOT_ADD_SELF: 'CONTACT_CANNOT_ADD_SELF',
  CONTACT_ALREADY_ADDED: 'CONTACT_ALREADY_ADDED',
  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',

  // ── Invitations ───────────────────────────────────────────────────────────
  INVITATION_CREATED: 'INVITATION_CREATED',
  INVITATION_BATCH_CREATED: 'INVITATION_BATCH_CREATED',
  INVITATION_LIST_RETRIEVED: 'INVITATION_LIST_RETRIEVED',
  INVITATION_RECEIVED_LIST_RETRIEVED: 'INVITATION_RECEIVED_LIST_RETRIEVED',
  INVITATION_PREVIEW_RETRIEVED: 'INVITATION_PREVIEW_RETRIEVED',
  INVITATION_ACCEPTED: 'INVITATION_ACCEPTED',
  INVITATION_CANCELLED: 'INVITATION_CANCELLED',

  INVITATION_USER_OR_CONTACT_REQUIRED: 'INVITATION_USER_OR_CONTACT_REQUIRED',
  INVITATION_BOTH_PROVIDED: 'INVITATION_BOTH_PROVIDED',
  INVITATION_ACTIVITY_FULL: 'INVITATION_ACTIVITY_FULL',
  INVITATION_CANNOT_INVITE_SELF: 'INVITATION_CANNOT_INVITE_SELF',
  INVITATION_USER_ALREADY_PARTICIPANT: 'INVITATION_USER_ALREADY_PARTICIPANT',
  INVITATION_ALREADY_PENDING: 'INVITATION_ALREADY_PENDING',
  INVITATION_EXTERNAL_CONTACT_NO_EMAIL: 'INVITATION_EXTERNAL_CONTACT_NO_EMAIL',
  INVITATION_EXTERNAL_CONTACT_ALREADY_PARTICIPANT:
    'INVITATION_EXTERNAL_CONTACT_ALREADY_PARTICIPANT',
  INVITATION_BATCH_EMPTY: 'INVITATION_BATCH_EMPTY',
  INVITATION_BATCH_TOO_MANY: 'INVITATION_BATCH_TOO_MANY',
  INVITATION_INVALID: 'INVITATION_INVALID',
  INVITATION_ALREADY_ACCEPTED: 'INVITATION_ALREADY_ACCEPTED',
  INVITATION_REJECTED: 'INVITATION_REJECTED',
  INVITATION_ALREADY_CANCELLED: 'INVITATION_ALREADY_CANCELLED',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_ACTIVITY_NOT_OPEN: 'INVITATION_ACTIVITY_NOT_OPEN',
  INVITATION_INVITEE_ALREADY_PARTICIPANT: 'INVITATION_INVITEE_ALREADY_PARTICIPANT',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_CANCEL_INVALID_STATUS: 'INVITATION_CANCEL_INVALID_STATUS',
  INVITATION_MANAGE_FORBIDDEN: 'INVITATION_MANAGE_FORBIDDEN',
} as const;

export type ApiCode = keyof typeof ApiCodes;
